
version: "3"
services:
  database:
    image: "postgres:10.5"
    container_name: "security-jdbc-database"
    ports:
      - "5400:5432"
    network_mode: bridge  
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/init.sql